name: flutter_mvvm_bloc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.5.0+1
  carousel_slider: ^4.2.1
  retrofit: ^4.1.0
  cached_network_image: ^3.3.1
  flutter_widget_from_html: ^0.15.1
  fpdart: ^1.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.1
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true